#pragma once
#ifndef __PLAYER_ANIMATION_STATE__
#define __PLAYER_ANIMATION_STATE__

enum PlayerAnimationState
{
	PLAYER_IDLE_RIGHT,
	PLAYER_IDLE_LEFT,
	PLAYER_IDLE_FRONT,
	PLAYER_IDLE_BACK,
	PLAYER_RUN_RIGHT,
	PLAYER_RUN_LEFT,
	PLAYER_RUN_FRONT,
	PLAYER_RUN_BACK,
	PLAYER_ATTACK_RIGHT,
	PLAYER_ATTACK_LEFT,
	PLAYER_ATTACK_FRONT,
	PLAYER_ATTACK_BACK,
	PLAYER_RANGE_RIGHT,
	PLAYER_RANGE_LEFT,
	PLAYER_RANGE_FRONT,
	PLAYER_RANGE_BACK,
	NUM_OF_ANIMATION_STATES
};

#endif /* defined (__PLAYER_ANIMATION_STATE__)*/