#pragma once
#ifndef __PLAYER_ANIMATION_STATE__
#define __PLAYER_ANIMATION_STATE__

enum PlayerAnimationState
{
	PLAYER_IDLE,
	PLAYER_WALK,
	PLAYER_WALK_RIGHT,
	PLAYER_WALK_LEFT,
	PLAYER_WALK_FRONT,
	PLAYER_WALK_BACK,
	PLAYER_ATTACK_RIGHT,
	PLAYER_ATTACK_LEFT,
	PLAYER_ATTACK_FRONT,
	PLAYER_ATTACK_BACK,
	PLAYER_RANGE_RIGHT,
	PLAYER_RANGE_LEFT,
	PLAYER_RANGE_FRONT,
	PLAYER_RANGE_BACK,
	NUM_OF_ANIMATION_STATES
};

#endif /* defined (__PLAYER_ANIMATION_STATE__)*/